Repository geoadmin/service-kml, pull requests merged in 2022-04, with the labels that each got.

#45 feature_BGDIINF_SB-2290: using a more recent version of Flask
  Pipfile
  Pipfile.lock
  app/settings.py
  tests/unit_tests/__init__.py
  tests/unit_tests/base.py
  wsgi.py
Labels: feature

#46 Normalized routes logging
  app/__init__.py
Labels: bug

#48 BGDIINF_SB-2346: Only check the kml file size and not the payload size
  app/helpers/utils.py
  app/routes.py
  tests/unit_tests/base.py
  tests/unit_tests/test_routes.py
Labels: bug

#50 BGDIINF_SB-2353: Fixed manual CI build
  buildspec.yml
Labels: bug

#52 BGDIINF_SB-2346: Avoid memory starting
  app/helpers/utils.py
  app/routes.py
Labels: bug

#51 New Release v1.4.1 - #patch
  app/helpers/utils.py
  app/routes.py
  buildspec.yml
Labels: new-release
