Repository geoadmin/service-kml, pull requests merged in 2022-02, with the labels that each got.

#36 BGDIINF_SB-2163: Fixed CI branch name resolution
  buildspec.yml
Labels: bug

#37 BGDIINF_SB-2201: Added extra DB fields
  app/helpers/dynamodb.py
  app/routes.py
  scripts/compress_file.py
  scripts/init_scripts.py
  tests/__init__.py
  tests/samples/updated-kml.xml.gz
  tests/samples/valid-kml.xml.gz
  tests/unit_tests/test_routes.py
Labels: feature

#38 BGDIINF_SB-2201: Cleanup unit tests and added some gzipped tests
  .pylintrc
  tests/samples/invalid-kml.xml.gz
  tests/unit_tests/base.py
  tests/unit_tests/test_routes.py
Labels: feature

#39 New Release v1.2.0 - #minor
  .pylintrc
  app/helpers/dynamodb.py
  app/routes.py
  buildspec.yml
  scripts/compress_file.py
  scripts/init_scripts.py
  tests/__init__.py
  tests/samples/invalid-kml.xml.gz
  tests/samples/updated-kml.xml.gz
  tests/samples/valid-kml.xml.gz
  tests/unit_tests/base.py
  tests/unit_tests/test_routes.py
Labels: new-release

#40 fix link to build status
  README.md
Labels: bug
